/**
 * Emit a seed as a plain .sql artifact.
 *
 * WHY NOT AN HTTP ENDPOINT. The obvious way to seed a remote database is a
 * `/seed` route on the deployed Worker. That puts an unauthenticated write
 * endpoint on the public internet, and seeding code in the production bundle.
 * Emitting SQL instead means:
 *
 *   - zero seed code ships in the Worker
 *   - the artifact is diffable and reviewable before it touches anything
 *   - it is applied by a human with an explicit, named command
 *
 * WHY NOT DUPLICATE THE INSERTS. Writing a second copy of every INSERT here
 * would drift from `seedProgram` the first time a column changed. Instead this
 * RECORDS what the real seeder emits, through a fake D1 that captures
 * statements instead of executing them. One source of truth; a test proves the
 * two paths produce identical rows.
 */

import type { RequestContext } from '../types';
import type { ProgramSpec } from './types';
import { seedProgram } from './seedProgram';
import { deterministicIds } from './deterministicIds';
import { seededId } from './deterministicIds';

interface Recorded {
  sql: string;
  binds: unknown[];
}

interface RecordedStatement {
  __sql: string;
  __binds: unknown[];
}

/**
 * A D1Database-shaped recorder.
 *
 * Only the surface `seedProgram` uses when `publish` is false: prepare, bind,
 * batch. It deliberately implements no read methods -- if the seeder ever
 * starts reading during the insert phase, this fails loudly rather than
 * silently emitting an incomplete artifact.
 */
class RecordingDb {
  readonly recorded: Recorded[] = [];

  prepare(sql: string): { bind: (...binds: unknown[]) => RecordedStatement } {
    return {
      bind: (...binds: unknown[]): RecordedStatement => ({ __sql: sql, __binds: binds }),
    };
  }

  async batch(statements: RecordedStatement[]): Promise<unknown[]> {
    for (const s of statements) {
      if (typeof s?.__sql !== 'string') {
        throw new Error('recorder received a statement it did not create');
      }
      this.recorded.push({ sql: s.__sql, binds: s.__binds });
    }
    return statements.map(() => ({ success: true }));
  }
}

/** Render a bound value as a SQL literal. */
function literal(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') {
    if (!Number.isFinite(v)) throw new Error(`refusing to emit non-finite number: ${v}`);
    // Integers only. A float reaching a *_cents column is the failure mode the
    // whole money design exists to prevent, so it is refused here too.
    if (!Number.isInteger(v)) throw new Error(`refusing to emit a non-integer number: ${v}`);
    return String(v);
  }
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (typeof v === 'string') return `'${v.replace(/'/g, "''")}'`;
  throw new Error(`refusing to emit unsupported bind type: ${typeof v}`);
}

/**
 * Inline bound values into a statement.
 *
 * The seeder's SQL uses `?` only as placeholders; none of its string literals
 * contain a question mark. The count is asserted rather than assumed, so a
 * template that ever breaks that rule fails here instead of producing a
 * subtly wrong artifact.
 */
function inline(rec: Recorded): string {
  const placeholders = (rec.sql.match(/\?/g) ?? []).length;
  if (placeholders !== rec.binds.length) {
    throw new Error(
      `placeholder/bind mismatch: ${placeholders} placeholders, ${rec.binds.length} binds in: ${rec.sql.slice(0, 120)}`,
    );
  }
  let i = 0;
  const sql = rec.sql.replace(/\?/g, () => literal(rec.binds[i++]));
  return `${sql.replace(/\s+/g, ' ').trim()};`;
}

export interface EmitOptions {
  /** Fixed timestamp so the artifact is stable across regenerations. */
  now?: string;
}

/**
 * Produce the SQL text that seeds one program.
 *
 * Ids are deterministic, derived from the program slug. Running the emitted SQL
 * a second time therefore collides on the primary key and aborts, rather than
 * creating a duplicate program that cannot be removed.
 */
export async function emitSeedSql(spec: ProgramSpec, opts: EmitOptions = {}): Promise<string> {
  const now = opts.now ?? '2026-01-01T00:00:00.000Z';
  const mint = deterministicIds(spec.slug);

  const ctx: RequestContext = {
    requestId: `seed-${spec.slug}`,
    session: null,
    ip: null,
    userAgent: null,
    route: 'seed',
    method: 'SEED',
  };

  const recorder = new RecordingDb();

  // publish:false keeps this to the insert phase, which performs no reads.
  const seeded = await seedProgram(
    recorder as unknown as D1Database,
    ctx,
    spec,
    { publish: false, idFactory: mint, now },
  );

  const lines: string[] = [];
  lines.push(`-- Seed: ${spec.name} (${spec.slug})`);
  lines.push(`-- Generated by npm run seed:build. Do not edit by hand.`);
  lines.push(`--`);
  lines.push(`-- Ids are deterministic, derived from the program slug, so running this`);
  lines.push(`-- file twice aborts on a primary-key collision instead of creating a`);
  lines.push(`-- second, unremovable copy of the program.`);
  lines.push('');

  for (const rec of recorder.recorded) lines.push(inline(rec));

  // The publish step, which in the live path reads the definition back before
  // flipping it. Here the lint and coverage checks have already run inside
  // seedProgram's pre-flight, so the transition itself is all that remains.
  lines.push('');
  lines.push('-- Publish each form definition. Guarded on status so re-running is inert.');
  for (const [stageKey, formId] of Object.entries(seeded.formDefinitionIds)) {
    lines.push(
      `UPDATE form_definitions SET status = 'published', published_at = ${literal(now)}, ` +
        `updated_at = ${literal(now)} WHERE id = ${literal(formId)} AND status = 'draft';`,
    );
    lines.push(
      `INSERT INTO audit_log (id, actor_user_id, actor_kind, actor_role, actor_organization_id, ` +
        `action, entity_type, entity_id, before_json, after_json, changed_fields_json, ` +
        `request_id, ip, user_agent, created_at) SELECT ${literal(seededId(`${spec.slug}/audit/form.published/${stageKey}`))}, NULL, 'system', NULL, NULL, ` +
        `'form_definition.published', 'form_definition', ${literal(formId)}, ` +
        `'{"status":"draft"}', '{"status":"published"}', '["status"]', ` +
        `${literal(`seed-${spec.slug}-${stageKey}`)}, NULL, NULL, ${literal(now)} ` +
        `WHERE EXISTS (SELECT 1 FROM form_definitions WHERE id = ${literal(formId)} AND status = 'published');`,
    );
  }

  lines.push('');
  return lines.join('\n');
}
