/**
 * Turn a migration into something that can be applied to production BY HAND.
 *
 *   node scripts/buildMigrationApply.mjs 0029
 *
 * WHY THIS EXISTS. `wrangler d1 migrations apply --remote` has failed on this
 * account with `The given account is not valid or is not authorized to access
 * this service [code: 7403]`. It was once believed that `--json` was what
 * avoided that, and that `migrations apply` -- which has no such flag -- could
 * therefore never work. THAT WAS WRONG: on 2026-10-08 a `d1 execute --json`
 * failed with the same 7403 and succeeded on an immediate retry. The 7403 is
 * intermittent, so try `npm run migrate:production:native` first and retry it
 * once before falling back to this file.
 *
 * What remains true is that the fallback has to carry the ledger row itself:
 *
 *   wrangler d1 execute <db> --remote --env production --yes --json --command=...
 *
 * which runs SQL and knows nothing about the `d1_migrations` ledger. That is
 * precisely how 0028 went wrong: its DDL ran, no ledger row was written, and
 * golive reported 27 applied against 28 on disk. The remedy then was to patch
 * the ledger afterwards. The remedy now is to stop separating the two.
 *
 * So this emits ONE file carrying the migration's own statements plus its
 * ledger row, and makes every statement idempotent so a half-applied run is
 * fixed by running it again rather than by unpicking it -- there is no
 * cross-statement transaction on this path.
 *
 * IT REFUSES WHAT IT CANNOT MAKE IDEMPOTENT. `DROP TRIGGER x` (0024 has one)
 * cannot be repeated safely, and a generator that silently emitted it would
 * produce a file that works once and fails confusingly forever after. Better
 * to say so and have a person decide.
 *
 * IT DOES NOT TOUCH PRODUCTION. It writes a file. A human runs it, which is
 * CLAUDE.md's second non-negotiable and the same line scripts/apply-sql.mjs
 * draws.
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** `CREATE TABLE x` -> `CREATE TABLE IF NOT EXISTS x`, for the three we use. */
const IDEMPOTENT = [
  [/\bCREATE\s+TABLE\s+(?!IF\s+NOT\s+EXISTS)/gi, 'CREATE TABLE IF NOT EXISTS '],
  [/\bCREATE\s+(UNIQUE\s+)?INDEX\s+(?!IF\s+NOT\s+EXISTS)/gi, (_m, u) => `CREATE ${u ?? ''}INDEX IF NOT EXISTS `],
  [/\bCREATE\s+TRIGGER\s+(?!IF\s+NOT\s+EXISTS)/gi, 'CREATE TRIGGER IF NOT EXISTS '],
  [/\bCREATE\s+VIEW\s+(?!IF\s+NOT\s+EXISTS)/gi, 'CREATE VIEW IF NOT EXISTS '],
];

/** Statements no repeat run can survive. Named rather than mangled. */
const REFUSE = [
  [/\bDROP\s+(TABLE|TRIGGER|INDEX|VIEW)\b(?!\s+IF\s+EXISTS)/i, 'a DROP without IF EXISTS'],
  [/\bALTER\s+TABLE\b/i, 'an ALTER TABLE, which SQLite cannot make conditional'],
];

export function buildApply(number) {
  const file = readdirSync(join(root, 'migrations')).find((f) => f.startsWith(`${number}_`));
  if (!file) throw new Error(`no migration starting ${number}_`);
  const src = readFileSync(join(root, 'migrations', file), 'utf8');

  for (const [pattern, why] of REFUSE) {
    if (pattern.test(src)) {
      throw new Error(
        `${file} contains ${why}. This generator cannot make it safe to re-run.\n` +
          'Apply it by hand, deliberately, and write the ledger row in the same batch.',
      );
    }
  }

  let body = src;
  for (const [pattern, to] of IDEMPOTENT) body = body.replace(pattern, to);

  return `-- GENERATED by scripts/buildMigrationApply.mjs from migrations/${file}
-- Do not edit. Re-generate:  node scripts/buildMigrationApply.mjs ${number}
--
-- Applying ${file} to production, through the only path that works on this
-- account:
--
--   npx wrangler d1 execute steward-production --remote --env production --yes \\
--     --json --command="$(cat scripts/sql/apply-${number}.sql)"
--
-- TRY \`npm run migrate:production:native\` FIRST, and retry it once if it
-- answers 7403: that error is intermittent, not a property of the command. It
-- was once believed that --json was what made a remote execute work and that
-- \`migrations apply\`, which has no such flag, could never succeed; a --json
-- command failed and then succeeded on a retry on 2026-10-08, which disproved
-- that. This file is the fallback for when the retry does not help.
--
-- EVERY STATEMENT IS IDEMPOTENT and the ledger row is written in the SAME run.
-- 0028's DDL was applied without its ledger row and golive then read 27 of 28;
-- separating the two is the mistake this file exists to make impossible. There
-- is no cross-statement transaction on this path, so a half-applied run is
-- fixed by running this again.

${body.trimEnd()}

-- The ledger. Without this the schema and \`npm run golive\` disagree, and the
-- next migration run cannot tell what is already applied.
INSERT OR IGNORE INTO d1_migrations (name) VALUES ('${file}');

-- Proof, in the same run that did the work. Expect applied = 1 and a count
-- matching the number of migrations on disk.
SELECT (SELECT COUNT(*) FROM d1_migrations WHERE name = '${file}') AS applied,
       (SELECT COUNT(*) FROM d1_migrations) AS ledger_rows;
`;
}

const number = process.argv[2];
if (number) {
  const out = join(root, 'scripts', 'sql', `apply-${number}.sql`);
  writeFileSync(out, buildApply(number));
  console.log(`wrote ${out}`);
}
