/**
 * Emit SQL that creates staff accounts.
 *
 *   npm run admin:sql -- admin.one@texans.com admin.two@texans.com
 *
 * Staff accounts are NOT created automatically when Cloudflare Access
 * authenticates someone. Access answers "is this a person our policy admits";
 * it does not answer "should this person see other nonprofits' audited
 * financial statements". Those stay separate decisions, so adding a staff
 * member is deliberately two steps: the Access policy, and this.
 *
 * Two admins from day one is a continuity requirement, not a preference: a
 * single admin unavailable during an open cycle means nobody can extend a
 * deadline, answer an applicant, or record a decision.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { seededId } from '../src/seed/deterministicIds';

const ROLE = 'admin';
const emails = process.argv.slice(2).map((e) => e.trim().toLowerCase()).filter(Boolean);

if (emails.length === 0) {
  console.error('usage: npm run admin:sql -- <email> [email...]');
  process.exit(1);
}
for (const e of emails) {
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(e)) {
    console.error(`refusing to emit a row for an address that is not an email: ${e}`);
    process.exit(1);
  }
}
if (emails.length < 2) {
  console.error(
    'WARNING: only one admin. A single admin is a continuity failure, not a\n' +
    '         security preference. Add a second before an open cycle.',
  );
}

const now = new Date().toISOString();
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const lines = [
  `-- Staff accounts. Generated by npm run admin:sql.`,
  `-- Apply with:`,
  `--   npx wrangler d1 execute steward-preview --remote --file=seeds/admins.sql`,
  `--`,
  `-- Ids are derived from the email, so re-running collides rather than`,
  `-- creating a second account for the same person.`,
  ``,
];

for (const email of emails) {
  const id = seededId(`user/${ROLE}/${email}`);
  lines.push(
    `INSERT INTO users (id, email, role, organization_id, display_name, is_active, created_at, updated_at) ` +
      `VALUES (${q(id)}, ${q(email)}, ${q(ROLE)}, NULL, ${q(email)}, 1, ${q(now)}, ${q(now)});`,
  );
  lines.push(
    `INSERT INTO audit_log (id, actor_user_id, actor_kind, actor_role, actor_organization_id, ` +
      `action, entity_type, entity_id, before_json, after_json, changed_fields_json, ` +
      `request_id, ip, user_agent, created_at) VALUES (` +
      `${q(seededId(`audit/user.created/${email}`))}, NULL, 'system', NULL, NULL, ` +
      `'user.created', 'user', ${q(id)}, NULL, ` +
      `${q(JSON.stringify({ email, role: ROLE, source: 'admin:sql' }))}, '["email","role"]', ` +
      `${q('admin-bootstrap')}, NULL, NULL, ${q(now)});`,
  );
}
lines.push('');

mkdirSync('seeds', { recursive: true });
writeFileSync('seeds/admins.sql', lines.join('\n'), 'utf8');
console.log(`seeds/admins.sql: ${emails.length} admin account(s)`);
for (const e of emails) console.log(`  ${e}`);
