/**
 * Sign in — the external front door, for grantees and applicants alike.
 *
 * This page did not exist. The endpoint behind it did, the hashed single-use
 * tokens did, the email template did, and the email itself already linked here
 * for "request another link" — but nothing ever asked a nonprofit for their
 * address, so there was no way into the portal except a link generated by
 * hand. A grantee who deleted the mail was locked out with nothing to click.
 *
 * ONE FIELD. A program director does this from a phone, between two other
 * jobs, months after the last time. Every extra control is a reason to give up
 * and email a staff member instead.
 *
 * THE ACKNOWLEDGEMENT IS ALWAYS THE SAME. Known address or not, this page says
 * the same sentence. "No account found" would make this a tool for discovering
 * which nonprofits applied for money, one address at a time. The server is
 * already careful about that; the UI has to be too, or the care is wasted.
 *
 * NO CLASSES FROM internal.css. That stylesheet is the dark staff surface and
 * this is the light applicant one. Borrowing across them has already produced
 * near-white text on a near-white ground once in this project.
 */

import { useCallback, useState } from 'react';
import type { FormEvent, ReactElement } from 'react';
import { ApiError } from './http';
import { authApi } from './authApi';
import { Turnstile } from './Turnstile';

interface Props {
  /** Public by design. Null when Turnstile is unconfigured; no widget renders. */
  turnstileSiteKey: string | null;
  /**
   * Why they are here.
   *
   * 'expired' is a returning user whose session ran out mid-task. Saying so is
   * the difference between "this is broken" and "this is normal".
   */
  reason?: 'expired' | null;
  /** Offered only when a program is actually open. */
  onSeeOpenGrants?: (() => void) | undefined;
}

type State =
  | { kind: 'asking' }
  | { kind: 'sending' }
  | { kind: 'sent'; message: string }
  | { kind: 'error'; message: string };

export function SignIn({ turnstileSiteKey, reason = null, onSeeOpenGrants }: Props): ReactElement {
  const [email, setEmail] = useState('');
  const [token, setToken] = useState<string | null>(null);
  const [state, setState] = useState<State>({ kind: 'asking' });

  const submit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault();
      const address = email.trim();
      if (address === '') return;
      setState({ kind: 'sending' });
      try {
        const res = await authApi.requestLink(address, token);
        setState({ kind: 'sent', message: res.message });
      } catch (err) {
        setState({
          kind: 'error',
          message:
            err instanceof ApiError
              ? err.message
              : 'We could not send that just now. Please try again.',
        });
      }
    },
    [email, token],
  );

  if (state.kind === 'sent') {
    return (
      <div className="card sign-in">
        <h2 tabIndex={-1} data-route-heading>
          Check your email
        </h2>
        <p>{state.message}</p>
        <p className="help">
          The link opens your grants and reports. It works once and it expires, so if it has
          been a while, come back here and ask for another.
        </p>
        <div className="actions">
          <button
            type="button"
            className="btn secondary"
            onClick={() => {
              setState({ kind: 'asking' });
              setToken(null);
            }}
          >
            Send another link
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="card sign-in">
      <h2 tabIndex={-1} data-route-heading>
        Sign in
      </h2>

      {reason === 'expired' ? (
        <p>
          Your sign-in has expired, which is normal — they are deliberately short-lived. Enter
          your email and we will send a new link.
        </p>
      ) : (
        <p>
          Enter the email address the Houston Texans Foundation has for your organization. We
          will send you a link to sign in. There is no password.
        </p>
      )}

      <form onSubmit={submit} noValidate>
        <div className="fields">
          <div className="field" data-wide="true">
            <label htmlFor="sign-in-email">Email address</label>
            <input
              id="sign-in-email"
              name="email"
              type="email"
              autoComplete="email"
              autoCapitalize="none"
              autoCorrect="off"
              spellCheck={false}
              inputMode="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              aria-describedby={state.kind === 'error' ? 'sign-in-error' : undefined}
              aria-invalid={state.kind === 'error' ? 'true' : undefined}
            />
          </div>
        </div>

        {/* Renders nothing when unconfigured, matching the server, which skips
            verification outside production when the SECRET is unset. If the two
            disagreed, this page would show a challenge nobody could pass. */}
        <Turnstile siteKey={turnstileSiteKey} onToken={setToken} />

        {state.kind === 'error' && (
          <p className="error" id="sign-in-error" role="alert">
            {state.message}
          </p>
        )}

        <div className="actions">
          <button
            type="submit"
            className="btn"
            disabled={state.kind === 'sending' || email.trim() === ''}
          >
            {state.kind === 'sending' ? 'Sending…' : 'Email me a link'}
          </button>
          {onSeeOpenGrants && (
            <button type="button" className="btn secondary" onClick={onSeeOpenGrants}>
              See open grants
            </button>
          )}
        </div>
      </form>
    </div>
  );
}
